### ISSUE TITLE
Can not run nipo/main.go

### ISSUE THREAD

**Issue by aahemm** [bashsiz/nipo#45]
Hi, 
I had some issue with importing nipo package. I am using this repo out of GOPATH. I tried to fix it using `go mod`. Now it looks fine.
Can I a create a pull request for that?
The error was:
`package nipo is not in GOROOT (/usr/local/go/src/nipo)`

**Comment by MortezaBashsiz** [comment]
Hi,

Thank you so much for contribution
Please create your pull request to branch "dev", I will check it

The issue will be closed, Please reopen if was needed
